# Generated by Django 4.0.6 on 2022-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='datePosted',
            field=models.DateTimeField(null=True),
        ),
    ]
