# Generated by Django 4.0.6 on 2022-09-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='personID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogapp.person'),
        ),
    ]
