# Generated by Django 4.0.6 on 2022-09-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='softDelete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
