# Generated by Django 4.1.1 on 2022-09-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blog_softdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committeName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('pizzaName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('sem', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingName', models.CharField(max_length=30)),
                ('pizzaTopping', models.ManyToManyField(to='blogapp.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriptionDate', models.DateTimeField(auto_now_add=True)),
                ('committeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.committee')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='Student',
            field=models.ManyToManyField(through='blogapp.Subscription', to='blogapp.student'),
        ),
    ]
