# Generated by Django 4.1.1 on 2022-09-12 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0007_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='committeeID',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='studentID',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='pizzaTopping',
        ),
        migrations.AlterField(
            model_name='blog',
            name='personID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
